### ISSUE TITLE
"Cannot read property 'fields' of undefined" while using multiple upload with onError callback 

### ISSUE THREAD

**Issue by chardlau** [dlau/koa-body#122]
## Promblem/Feature Request Summary
"Cannot read property 'fields' of undefined" while using multiple upload with onError callback.
And I found line 84 to 109 of source code 'index.js' cause the problem.

## Environment Information

  * koa-body: 4.0.4
  * Koa: 2.6.1
  * Node.js: 8.12.0

## Current Behavior
TypeError: Cannot read property 'fields' of undefined

## Steps to Reproduce

1. Part of the code 
```
...
router.post('/', koaBody({
    multipart: true,
    formidable: {
        uploadDir: config.uploadDir,
        maxFileSize: 1 * 1024 * 1024,
        keepExtensions: false,
        multiples: false,
    },
    onError: (err, ctx) => {
        console.log('Failed');
        ctx.body = "Failed";
    },
}), async (ctx, next) => {
    const files = ctx.request.files || {};
    for (let file in files) {
        console.log('file.name: ', file.name);
    }
    ctx.body = "Done";
});
```
2. Use curl to upload a file with size larger than 1M.

## Expected Behavior
curl got 'failed' as response.

## Possible Solution
Line 84 to 109 of source code 'index.js' 
```
    ...
    return bodyPromise.catch(function(parsingError) {
     ...
      return next();
    })
    .then(function(body) {
          ...
          ctx.request.body = body.fields;
          ctx.request.files = body.files;
          ... 
      }
      ...
    })
    ...
```
The 'then' callback may be called with undefined as parameter 'body', because bodyPromise.catch's callback function ```return next()```, while next here I return is nothing.

Should I change catch's callback function ```return next()``` to ```return next() || {}```
or just give parameter 'body' a default value like ```... function(body = {}) { ...``` and change the order of then and catch ？

**Comment by MarkHerhold** [comment]
I don't think we should change the codebase to `return next() || {}` because `next()` is how the next middleware is called in Koa. I'm not even sure what would happen if you returned an object instead of a promise.

I see two options:

### 1. Custom error handler
The downside with this approach is that you have to figure out how to differentiate a koa-body error (actually formidable under the hood) VS other errors.

```js
// other app code above here

// error handline middleware
app.use(async function (ctx, next) {
  console.log('loaded error handling middleware');
  try {
    await next();
  } catch (err) {
    // this is where you handle - Error: maxFileSize exceeded, received 1113965 bytes of file data
    // I would map this to a 4xx error code
    console.log('error', err);
  }
});
app.use(router.routes());
app.listen(port);
```

### 2. Custom error handler and `throw` in `.onError`
Add the same error handling middleware above but change your `onError` handler to throw. Ideally, you would re-cast this error as something you can recognize in the error handling middleware from step 1. I use [Boom](https://github.com/hapijs/boom) to help with this.

```js
    onError: (err, ctx) => {
      throw err; // optionally recast as something we can recognize in the error middleware
    },
```
